# Generated by Django 2.1 on 2019-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
